#Makefile para hello world

# Declarar el nombre del proyecto que será construido que tiene que
# ser igual que el archivo de código sin extensión
IDOS_PROJECT = coap_server

# Declarar dónde está IDOS
IDOS = ../..

APPS += coap

# Regla por defecto
all: $(IDOS_PROJECT)

# Incorporar el resto de los makefile
include $(IDOS)/tools/make/idos.mk
